name: Zip and Upload Database

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zip_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create zip of database files
      run: |
        mkdir -p output
        zip -r output/database_backup.zip path/to/database/files

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp output/database_backup.zip s3://your-bucket-name/path/to/destination/
